// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Claims carried by the access token.
 */
export type AccessTokenClaims = { 
/**
 * User id, as a UUID string.
 */
sub: string, 
/**
 * Token id, for revocation.
 */
jti: string, 
/**
 * Issued at, seconds since the epoch.
 */
iat: number, 
/**
 * Expiry, seconds since the epoch.
 */
exp: number, };
