// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { id: string, filename: string, content_type: string, size_bytes: number, 
/**
 * Persisted so the list reserves space and does not reflow while scrolling
 * (RNF-04).
 */
width: number | null, height: number | null, 
/**
 * `null` when the attachment was not migrated (RF-25a).
 */
url: string | null, skip_reason: string | null, };
