// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One already-uploaded object being attached to a message. The backend confirms
 * it exists in R2 with a `HEAD` before persisting (SRS §6.2).
 */
export type AttachmentInput = { r2_key: string, filename: string, content_type: string, size_bytes: number, width?: number, height?: number, };
