// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUser } from "./CurrentUser";

/**
 * The token pair. The refresh token is opaque and is stored by the Rust core in
 * the Windows credential vault — never in `localStorage` (RF-01b).
 */
export type AuthResponse = { access_token: string, refresh_token: string, 
/**
 * Access token lifetime in seconds.
 */
expires_in: number, user: CurrentUser, };
