// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of the `BRIDGE_STATUS` dispatch and of `GET /admin/bridge/status`.
 * Sent only to administrators. A permanent bridge that dies silently is worse
 * than no bridge at all.
 */
export type BridgeStatus = { connected: boolean, 
/**
 * Undelivered rows in `bridge_outbox`.
 */
queue_depth: number, last_error: string | null, };
