// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageOrigin } from "./MessageOrigin";

/**
 * Present when the message crossed the Discord bridge (RF-29).
 */
export type BridgeInfo = { origin: MessageOrigin, };
