// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelType } from "./ChannelType";
import type { PermissionMask } from "./PermissionMask";
import type { Snowflake } from "./Snowflake";
import type { Timestamp } from "./Timestamp";
import type { UserSummary } from "./UserSummary";

export type Channel = { id: string, guild_id: string | null, category_id: string | null, name: string, topic: string | null, type: ChannelType, position: number, bridge_enabled: boolean, discord_channel_id: Snowflake | null, 
/**
 * Only present on `dm` and `group_dm`.
 */
participants: Array<UserSummary> | null, 
/**
 * The requester's already-resolved mask (SRS §5.3). The client uses it to
 * enable or hide controls and never re-implements resolution.
 */
permissions: PermissionMask, created_at: Timestamp, };
