// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverwriteTarget } from "./OverwriteTarget";
import type { PermissionMask } from "./PermissionMask";

/**
 * `PUT /channels/{id}/permissions/{target_type}/{target_id}`.
 */
export type ChannelOverwrite = { channel_id: string, target_type: OverwriteTarget, target_id: string, allow: PermissionMask, deny: PermissionMask, };
