// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /guilds/{id}/channels/positions` — batch reorder, transactional.
 */
export type ChannelPosition = { id: string, position: number, category_id?: string | null, };
