// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors the `channel_type` enum in the schema.
 */
export type ChannelType = "text" | "voice" | "dm" | "group_dm";
