// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Opcode } from "./Opcode";

/**
 * A server frame that is not a dispatch: `HELLO`, `HEARTBEAT_ACK`,
 * `INVALID_SESSION` and `RECONNECT`.
 */
export type ControlFrame<T> = { op: Opcode, d?: T, };
