// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentInput } from "./AttachmentInput";

/**
 * `POST /channels/{id}/messages`.
 *
 * Mentions are **not** in this body: the server extracts them from `content`.
 * A client-supplied list is trustworthy only until someone opens DevTools.
 */
export type CreateMessageRequest = { content: string, 
/**
 * Client-generated. Idempotent for 60 s within the same channel: repeating
 * it returns the existing message with `200` instead of `201`.
 */
nonce?: string, reply_to_id?: string, attachments: Array<AttachmentInput>, };
