// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /dms`. With a single recipient the server resolves the existing 1:1
 * channel instead of creating another (RF-18).
 */
export type CreateDmRequest = { recipient_ids: Array<string>, };
