// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateInviteRequest = { guild_id?: string, max_uses?: number, 
/**
 * Lifetime in seconds. Absent means it never expires.
 */
expires_in?: number, };
