// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelType } from "./ChannelType";

export type CreateChannelRequest = { name: string, type: ChannelType, category_id?: string, topic?: string, position?: number, };
