// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMask } from "./PermissionMask";

export type CreateRoleRequest = { name: string, color?: string, position?: number, permissions?: PermissionMask, hoist?: boolean, };
