// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceStatus } from "./PresenceStatus";
import type { Snowflake } from "./Snowflake";
import type { Timestamp } from "./Timestamp";

/**
 * `GET /users/@me`. Carries the fields no one else may see.
 */
export type CurrentUser = { id: string, email: string | null, username: string, display_name: string | null, avatar_url: string | null, accent_color: string | null, bio: string | null, discord_user_id: Snowflake | null, 
/**
 * The user's own status, which is the only place `invisible` is reported.
 */
status: PresenceStatus, created_at: Timestamp, };
