// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of linking: how many ghost messages were reattributed.
 */
export type DiscordLinkResponse = { reattributed_messages: number, };
