// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake";

/**
 * `POST /users/@me/discord-link` (RF-26a). Transactional on the server.
 */
export type DiscordLinkRequest = { discord_user_id: Snowflake, };
