// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ready } from "./Ready";
import type { Resumed } from "./Resumed";
import type { RoomLeave } from "./RoomLeave";
import type { RoomParticipantAdd } from "./RoomParticipantAdd";
import type { RoomParticipantRemove } from "./RoomParticipantRemove";
import type { RoomState } from "./RoomState";
import type { ShareEvent } from "./ShareEvent";

/**
 * Every dispatch event (`docs/websocket.md` §5).
 *
 * Adjacently tagged so it serialises exactly as `{"t": "NAME", "d": {…}}`, which
 * is what the envelope requires once flattened into `DispatchFrame`.
 *
 * Every event here is replayable. v1 had one ephemeral event (`TYPING_START`)
 * that consumed a sequence without entering the resume buffer; with it gone,
 * the buffer holds everything the session ever sent.
 */
export type DispatchEvent = { "t": "READY", "d": Ready } | { "t": "RESUMED", "d": Resumed } | { "t": "ROOM_JOIN", "d": RoomState } | { "t": "ROOM_LEAVE", "d": RoomLeave } | { "t": "ROOM_PARTICIPANT_ADD", "d": RoomParticipantAdd } | { "t": "ROOM_PARTICIPANT_REMOVE", "d": RoomParticipantRemove } | { "t": "SHARE_START", "d": ShareEvent } | { "t": "SHARE_STOP", "d": ShareEvent };
