// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeStatus } from "./BridgeStatus";
import type { Category } from "./Category";
import type { Channel } from "./Channel";
import type { DmParticipantEvent } from "./DmParticipantEvent";
import type { Member } from "./Member";
import type { Message } from "./Message";
import type { MessageBulkDelete } from "./MessageBulkDelete";
import type { MessageDelete } from "./MessageDelete";
import type { PermissionsStale } from "./PermissionsStale";
import type { Presence } from "./Presence";
import type { ReactionEvent } from "./ReactionEvent";
import type { ReadState } from "./ReadState";
import type { Ready } from "./Ready";
import type { Resumed } from "./Resumed";
import type { Role } from "./Role";
import type { TypingStart } from "./TypingStart";
import type { VoiceState } from "./VoiceState";

/**
 * Every dispatch event (`docs/protocol/websocket.md` §5).
 *
 * Adjacently tagged so it serialises exactly as `{"t": "NAME", "d": {…}}`, which
 * is what the envelope requires once flattened into `DispatchFrame`.
 */
export type DispatchEvent = { "t": "READY", "d": Ready } | { "t": "RESUMED", "d": Resumed } | { "t": "MESSAGE_CREATE", "d": Message } | { "t": "MESSAGE_UPDATE", "d": Message } | { "t": "MESSAGE_DELETE", "d": MessageDelete } | { "t": "MESSAGE_BULK_DELETE", "d": MessageBulkDelete } | { "t": "REACTION_ADD", "d": ReactionEvent } | { "t": "REACTION_REMOVE", "d": ReactionEvent } | { "t": "TYPING_START", "d": TypingStart } | { "t": "CHANNEL_CREATE", "d": Channel } | { "t": "CHANNEL_UPDATE", "d": Channel } | { "t": "CHANNEL_DELETE", "d": Channel } | { "t": "CATEGORY_CREATE", "d": Category } | { "t": "CATEGORY_UPDATE", "d": Category } | { "t": "CATEGORY_DELETE", "d": Category } | { "t": "ROLE_CREATE", "d": Role } | { "t": "ROLE_UPDATE", "d": Role } | { "t": "ROLE_DELETE", "d": Role } | { "t": "GUILD_MEMBER_ADD", "d": Member } | { "t": "GUILD_MEMBER_UPDATE", "d": Member } | { "t": "GUILD_MEMBER_REMOVE", "d": Member } | { "t": "PERMISSIONS_STALE", "d": PermissionsStale } | { "t": "PRESENCE_UPDATE", "d": Presence } | { "t": "VOICE_STATE_UPDATE", "d": VoiceState } | { "t": "DM_CHANNEL_CREATE", "d": Channel } | { "t": "DM_PARTICIPANT_ADD", "d": DmParticipantEvent } | { "t": "DM_PARTICIPANT_REMOVE", "d": DmParticipantEvent } | { "t": "READ_STATE_UPDATE", "d": ReadState } | { "t": "BRIDGE_STATUS", "d": BridgeStatus };
