// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `DM_PARTICIPANT_ADD` and `DM_PARTICIPANT_REMOVE`.
 */
export type DmParticipantEvent = { channel_id: string, user_id: string, };
