// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake";

/**
 * `POST /admin/bridge/channels/{id}` — enables the bridge and registers the
 * webhook. The token itself never reaches the database (RNF-15); only the
 * reference to the environment variable holding it does.
 */
export type EnableBridgeRequest = { 
/**
 * Discord channel snowflake this channel mirrors.
 */
discord_channel_id: Snowflake, discord_webhook_id: Snowflake, 
/**
 * Name of the environment variable holding the webhook token,
 * e.g. `DISCORD_WEBHOOK_GERAL`.
 */
token_ref: string, };
