// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every `code` the API can return (`docs/rest-api.md` §3, plus the
 * domain-specific codes named elsewhere in the contract).
 */
export type ErrorCode = "VALIDATION_FAILED" | "UNAUTHENTICATED" | "TOKEN_EXPIRED" | "TOKEN_REUSED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "RATE_LIMITED" | "INTERNAL" | "ROOM_CAPACITY" | "REPLICA_STALE" | "UPSTREAM_FAILURE";
