// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

export type ErrorBody = { 
/**
 * `SCREAMING_SNAKE_CASE`, stable, used in client logic.
 */
code: string, 
/**
 * Portuguese, displayable. Never carries internal detail.
 */
message: string, 
/**
 * Only present on `VALIDATION_FAILED`.
 */
details: Array<FieldError> | null, request_id: string, };
