// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorBody } from "./ErrorBody";

/**
 * Wrapper so every error response is `{ "error": { … } }`.
 */
export type ErrorResponse = { error: ErrorBody, };
