// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake";
import type { Timestamp } from "./Timestamp";

export type Guild = { id: string, name: string, icon_url: string | null, owner_id: string, discord_guild_id: Snowflake | null, created_at: Timestamp, };
