// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";

/**
 * `op: 2`.
 */
export type Identify = { 
/**
 * The same access token used by REST. The connection does **not** drop when
 * it expires: authentication is checked at identification time only.
 */
token: string, client: ClientInfo, };
