// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

export type Invite = { id: string, code: string, created_by: string, guild_id: string | null, max_uses: number, uses: number, expires_at: Timestamp | null, revoked_at: Timestamp | null, created_at: Timestamp, };
