// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * `GET /invites/{code}` — public. Carries only validity and the guild name, so
 * an unauthenticated caller learns nothing about the server structure.
 */
export type InvitePreview = { code: string, valid: boolean, guild_name: string | null, expires_at: Timestamp | null, };
