// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";
import type { UserSummary } from "./UserSummary";

/**
 * A guild member. `roles` holds role ids; the role objects come from the guild.
 */
export type Member = { user: UserSummary, guild_id: string, nickname: string | null, roles: Array<string>, joined_at: Timestamp, banned_at: Timestamp | null, };
