// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors the `message_origin` enum in the schema.
 */
export type MessageOrigin = "internal" | "discord";
