// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { BridgeInfo } from "./BridgeInfo";
import type { Reaction } from "./Reaction";
import type { ReplyPreview } from "./ReplyPreview";
import type { Timestamp } from "./Timestamp";
import type { UserSummary } from "./UserSummary";

export type Message = { id: string, channel_id: string, author: UserSummary, content: string, reply_to: ReplyPreview | null, attachments: Array<Attachment>, reactions: Array<Reaction>, is_pinned: boolean, edited_at: Timestamp | null, created_at: Timestamp, 
/**
 * Echoed back only to the session that sent the message, so the optimistic
 * insert can be reconciled. `null` for every other session.
 */
nonce: string | null, bridge: BridgeInfo | null, };
