// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuthStartResponse = { authorize_url: string, attempt_id: string, poll_secret: string, expires_in: number, };
