// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frame opcode (`docs/protocol/websocket.md` §2.1). Serialised as an integer.
 */
export type Opcode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
