// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overwrite target, mirroring the `overwrite_target` enum in the schema.
 */
export type OverwriteTarget = "role" | "member";
