// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The cursor trio. `before`, `after` and `around` are mutually exclusive.
 */
export type PageQuery = { before: string | null, after: string | null, around: string | null, limit: number | null, };
