// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /auth/pair`. The code was handed to the user by the bot, ephemerally,
 * inside Discord.
 */
export type PairRequest = { code: string, };
