// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A permission bitmask on the wire: decimal digits in a string.
 */
export type PermissionMask = string;
