// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceStatus } from "./PresenceStatus";

/**
 * One entry of `READY.presences` and the body of `PRESENCE_UPDATE`.
 */
export type Presence = { user_id: string, status: PresenceStatus, };
