// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PresignResponse = { r2_key: string, upload_url: string, expires_in: number, };
