// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RF-04. `invisible` is reported to third parties as `offline`; only the user
 * themself ever sees it (`docs/protocol/websocket.md` §5).
 */
export type PresenceStatus = "online" | "idle" | "dnd" | "invisible" | "offline";
