// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a publication carries: a screen, or a face (ADR-0038).
 *
 * The pair (person, source) is the unit of the domain. A person may hold one
 * of each at the same time, and each is started, stopped, watched and left on
 * its own.
 */
export type PublicationSource = "screen" | "camera";
