// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicationSource } from "./PublicationSource";
import type { Timestamp } from "./Timestamp";

/**
 * One live publication of one person.
 */
export type Publication = { source: PublicationSource, 
/**
 * When this publication went live, from the server (RF-34).
 *
 * Not the moment the viewer joined: someone who arrives twenty minutes in
 * has to see twenty minutes, not zero.
 */
since: Timestamp, };
