// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { Channel } from "./Channel";
import type { Member } from "./Member";
import type { Role } from "./Role";

export type ReadyGuild = { id: string, name: string, icon_url: string | null, owner_id: string, categories: Array<Category>, channels: Array<Channel>, roles: Array<Role>, members: Array<Member>, member_count: number, };
