// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { CurrentUser } from "./CurrentUser";
import type { Presence } from "./Presence";
import type { ReadState } from "./ReadState";
import type { ReadyGuild } from "./ReadyGuild";
import type { VoiceState } from "./VoiceState";

/**
 * `READY` payload (§3.1). Carries **structure**, never history: a `READY` that
 * loaded messages would make startup O(n) in server size.
 */
export type Ready = { session_id: string, user: CurrentUser, 
/**
 * Only guilds and channels the user can `VIEW_CHANNEL` at identification.
 */
guilds: Array<ReadyGuild>, dm_channels: Array<Channel>, read_states: Array<ReadState>, presences: Array<Presence>, voice_states: Array<VoiceState>, 
/**
 * Heartbeat interval echoed for clients that reconnect without a new HELLO.
 */
heartbeat_interval_ms: number, };
