// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUser } from "./CurrentUser";
import type { RoomState } from "./RoomState";

/**
 * `READY` payload (§3.1).
 *
 * `room` is `None` whenever the user is not in a Discord voice channel, which
 * is most of the time: the app sits in the tray and only has something to show
 * when Discord says so (ADR-0011).
 */
export type Ready = { session_id: string, user: CurrentUser, room?: RoomState, 
/**
 * Heartbeat interval echoed for clients that reconnect without a new HELLO.
 */
heartbeat_interval_ms: number, };
