// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadState = { channel_id: string, last_read_message_id: string | null, 
/**
 * Authoritative on the server; the client displays it and never recomputes
 * it (`docs/protocol/websocket.md` §6.5).
 */
mention_count: number, muted: boolean, };
