// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /admin/bridge/reconcile` — result of one RF-31a pass.
 */
export type ReconcileReport = { channels_examined: number, messages_examined: number, messages_requeued: number, 
/**
 * Divergences that could not be resolved and need a human.
 */
unresolved: Array<string>, };
