// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /auth/register`. Consumes the invite in the same transaction.
 */
export type RegisterRequest = { invite_code: string, email: string, username: string, password: string, };
