// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enough of the referenced message to render the reply header (RF-14).
 */
export type ReplyPreview = { id: string, author_username: string, excerpt: string, };
