// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `op: 3`.
 */
export type Resume = { token: string, session_id: string, last_seq: number, };
