// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMask } from "./PermissionMask";
import type { Timestamp } from "./Timestamp";

/**
 * A role. `permissions` travels as a decimal string (§6.4).
 */
export type Role = { id: string, guild_id: string, name: string, color: string | null, position: number, permissions: PermissionMask, 
/**
 * The implicit `@everyone` role.
 */
is_default: boolean, hoist: boolean, created_at: Timestamp, };
