// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomParticipant } from "./RoomParticipant";
import type { Snowflake } from "./Snowflake";

/**
 * Body of `ROOM_PARTICIPANT_ADD`.
 */
export type RoomParticipantAdd = { discord_channel_id: Snowflake, participant: RoomParticipant, };
