// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the server took the client out of a room. `Left` is the ordinary case;
 * the other two exist so the UI can say something true instead of "disconnected".
 */
export type RoomLeaveReason = "left" | "access_revoked" | "replica_stale";
