// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Publication } from "./Publication";
import type { UserSummary } from "./UserSummary";

/**
 * Someone present in a room.
 */
export type RoomParticipant = { user: UserSummary, 
/**
 * What this person is transmitting right now, empty when nothing.
 *
 * A list, and not a pair of booleans, because the viewer builds one tile
 * per entry: adding a source must not add a field to everything that
 * renders a participant (ADR-0038).
 */
publications: Array<Publication>, };
