// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicationSource } from "./PublicationSource";

/**
 * `POST /rooms/{discord_channel_id}/token`.
 */
export type RoomTokenRequest = { 
/**
 * Everything the client intends to have live, not just what it is starting
 * now (ADR-0038).
 *
 * The list is read as the whole intent: sources named here are claimed,
 * sources left out are given back. Empty is a viewer, and a viewer is never
 * refused because the publisher slots are full.
 *
 * Declaring the full set is what makes the call idempotent — the client
 * renews its token every hour (RNF-06), and a renewal must not be read as
 * a second publisher nor drop the slot of a source already on the air.
 */
publish: Array<PublicationSource>, };
