// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /rooms/{discord_channel_id}/token`.
 */
export type RoomTokenRequest = { 
/**
 * Whether the client intends to publish a screen. Drives the admission
 * guard: a viewer is never refused because the publisher slots are full.
 */
publish: boolean, };
