// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomLeaveReason } from "./RoomLeaveReason";
import type { Snowflake } from "./Snowflake";

/**
 * Body of `ROOM_LEAVE`.
 */
export type RoomLeave = { discord_channel_id: Snowflake, reason: RoomLeaveReason, };
