// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";
import type { UserSummary } from "./UserSummary";

/**
 * Someone present in a room.
 */
export type RoomParticipant = { user: UserSummary, publishing: boolean, 
/**
 * When this person's screen went live, from the server (RF-34).
 *
 * Not the moment the viewer joined: someone who arrives twenty minutes in
 * has to see twenty minutes, not zero. `None` when not publishing.
 */
publishing_since?: Timestamp, };
