// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserSummary } from "./UserSummary";

/**
 * Someone present in a room. Presence here means "connected to the Discord
 * voice channel", which is the only definition the product has.
 */
export type RoomParticipant = { user: UserSummary, publishing: boolean, };
