// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomParticipant } from "./RoomParticipant";
import type { Snowflake } from "./Snowflake";

/**
 * The full state of one room, carried by `ROOM_JOIN`.
 */
export type RoomState = { discord_channel_id: Snowflake, discord_guild_id: Snowflake, 
/**
 * Human-readable name of the Discord voice channel, for the window title.
 */
channel_name: string, participants: Array<RoomParticipant>, };
