// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * `GET /search`. Scope is `guild_id` **or** `channel_id`; there is no global
 * search without a scope.
 */
export type SearchQuery = { q: string, guild_id?: string, channel_id?: string, author_id?: string, 
/**
 * Inclusive lower bound on `created_at`.
 */
since?: Timestamp, 
/**
 * Exclusive upper bound on `created_at`.
 */
until?: Timestamp, 
/**
 * Keyset cursor: results strictly older than this message id.
 */
before?: string, limit?: number, };
