// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * One hit. Carries the neighbouring ids so the client can open the channel with
 * `around` without a second round trip.
 */
export type SearchHit = { message: Message, previous_message_id: string | null, next_message_id: string | null, };
