// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake";

/**
 * Body of `SHARE_START` and `SHARE_STOP`. Fed exclusively by LiveKit webhooks,
 * never by the client.
 */
export type ShareEvent = { discord_channel_id: Snowflake, user_id: string, };
