// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicationSource } from "./PublicationSource";
import type { Snowflake } from "./Snowflake";
import type { Timestamp } from "./Timestamp";

/**
 * Body of `SHARE_START`. Fed exclusively by LiveKit webhooks, never by the
 * client.
 *
 * Separate from `ShareStop` because it carries `started_at`, and a stop event
 * with a start time would be a field that is always a lie.
 *
 * `source` says which publication started (ADR-0038): the same person emits one
 * of these per source, and a client that only knew about screens would silently
 * treat a camera as one.
 */
export type ShareStart = { discord_channel_id: Snowflake, user_id: string, source: PublicationSource, started_at: Timestamp, };
