// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake";
import type { Timestamp } from "./Timestamp";

/**
 * Body of `SHARE_START`. Fed exclusively by LiveKit webhooks, never by the
 * client.
 *
 * Separate from `ShareStop` because it carries `started_at`, and a stop event
 * with a start time would be a field that is always a lie.
 */
export type ShareStart = { discord_channel_id: Snowflake, user_id: string, started_at: Timestamp, };
