// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Discord snowflake. `BIGINT` in the schema, decimal string on the wire for
 * the same precision reason as `PermissionMask`.
 */
export type Snowflake = string;
