// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An instant on the wire, always RFC 3339 with offset.
 */
export type Timestamp = string;
