// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * `TYPING_START`. Ephemeral, never persisted, never replayed on resume (RF-13).
 */
export type TypingStart = { channel_id: string, user_id: string, expires_at: Timestamp, };
