// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /users/@me`. Absent field = keep, `null` = clear (§1).
 */
export type UpdateCurrentUserRequest = { display_name?: string | null, avatar_url?: string | null, bio?: string | null, accent_color?: string | null, };
