// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMask } from "./PermissionMask";

export type UpdateRoleRequest = { name?: string, color?: string | null, position?: number, permissions?: PermissionMask, hoist?: boolean, };
