// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /voice-states/@me`. The client is the source of truth for these two
 * flags and nothing else.
 */
export type UpdateVoiceStateRequest = { self_mute?: boolean, self_deaf?: boolean, };
