// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceStatus } from "./PresenceStatus";

/**
 * `PATCH /users/@me/presence`.
 */
export type UpdatePresenceRequest = { status: PresenceStatus, };
