// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateMemberRequest = { nickname?: string | null, 
/**
 * Requires `MANAGE_ROLES`; the nickname alone can be changed by the member.
 */
roles?: Array<string>, };
