// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * Public profile (`GET /users/{id}`).
 */
export type User = { id: string, username: string, display_name: string | null, avatar_url: string | null, accent_color: string | null, bio: string | null, is_migrated: boolean, created_at: Timestamp, };
