// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The author/participant shape embedded in messages and channels
 * (`docs/api/rest-api.md` §7).
 */
export type UserSummary = { id: string, username: string, display_name: string | null, avatar_url: string | null, accent_color: string | null, 
/**
 * Ghost user imported from the Discord history (RF-26).
 */
is_migrated: boolean, };
