// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snowflake } from "./Snowflake";

/**
 * A user as seen by others in a room.
 */
export type UserSummary = { id: string, discord_user_id: Snowflake, username: string, display_name: string | null, avatar_url: string | null, };
