// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of `voice_states`, and the body of `VOICE_STATE_UPDATE`.
 *
 * `channel_id: null` means the user left. This event is fed exclusively by the
 * LiveKit webhooks received by the backend, never by the client (RF-20).
 */
export type VoiceState = { user_id: string, channel_id: string | null, self_mute: boolean, self_deaf: boolean, streaming: boolean, };
