// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /channels/{id}/voice-token`. The backend checks `CONNECT_VOICE` and the
 * RNF-10 guards before issuing.
 */
export type VoiceTokenRequest = { 
/**
 * Whether the client intends to publish a camera. Drives the three-publisher
 * guard: a listener is never refused because the cameras are full.
 */
publish_camera: boolean, };
