// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VoiceTokenResponse = { token: string, 
/**
 * WebSocket URL of the SFU.
 */
url: string, 
/**
 * LiveKit room name for this channel.
 */
room: string, 
/**
 * Token lifetime in seconds, always ≤ 3600 (RNF-07).
 */
expires_in: number, };
