//! Pairing codes: generation and hashing (RF-01).
//!
//! The code is a bearer credential with a five-minute life. It is generated by
//! the bot, shown once inside Discord, and exchanged for a token pair. Only the
//! hash is ever persisted, so a database dump hands out nothing usable.

use rand::Rng;
use sha2::{Digest, Sha256};

use crate::validation::{PAIRING_CODE_ALPHABET, PAIRING_CODE_LEN};

/// A freshly generated code, in clear. Deliberately not `Clone` and not
/// `Debug`: the only correct things to do with it are show it to its owner once
/// and hash it.
pub struct PairingCode(String);

impl PairingCode {
    /// Draw a new code from the unambiguous alphabet.
    pub fn generate() -> Self {
        let mut rng = rand::rng();
        let code = (0..PAIRING_CODE_LEN)
            .map(|_| {
                let i = rng.random_range(0..PAIRING_CODE_ALPHABET.len());
                PAIRING_CODE_ALPHABET[i] as char
            })
            .collect();
        Self(code)
    }

    /// The clear code, to be shown to the user exactly once.
    pub fn expose(&self) -> &str {
        &self.0
    }

    pub fn hash(&self) -> String {
        hash_code(&self.0)
    }
}

/// Lowercase hex SHA-256 of a code.
///
/// SHA-256 and not Argon2, for the same reason the refresh token uses SHA-256:
/// the input is high-entropy and drawn uniformly, so there is no dictionary to
/// attack, and a slow hash here would only tax the honest path.
pub fn hash_code(code: &str) -> String {
    let digest = Sha256::digest(code.as_bytes());
    let mut out = String::with_capacity(64);
    for byte in digest {
        use std::fmt::Write as _;
        // Escrever em String nao falha; o Result existe so pela assinatura.
        let _ = write!(out, "{byte:02x}");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::validation::pairing_code;
    use std::collections::HashSet;

    #[test]
    fn generated_codes_pass_their_own_validation() {
        for _ in 0..200 {
            let code = PairingCode::generate();
            assert_eq!(
                pairing_code(code.expose()),
                Ok(()),
                "gerou codigo invalido: {}",
                code.expose()
            );
        }
    }

    #[test]
    fn generated_codes_do_not_repeat_in_a_small_sample() {
        let codes: HashSet<String> = (0..500)
            .map(|_| PairingCode::generate().expose().to_owned())
            .collect();
        assert_eq!(codes.len(), 500, "colisao em 500 amostras");
    }

    #[test]
    fn hash_is_64_hex_characters() {
        let hash = hash_code("ABCD2345");
        assert_eq!(hash.len(), 64, "a coluna e CHAR(64)");
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
        assert!(hash.chars().all(|c| !c.is_ascii_uppercase()));
    }

    #[test]
    fn hash_is_stable_and_distinguishes_codes() {
        assert_eq!(hash_code("ABCD2345"), hash_code("ABCD2345"));
        assert_ne!(hash_code("ABCD2345"), hash_code("ABCD2346"));
    }

    #[test]
    fn hash_matches_a_known_vector() {
        // SHA-256("ABCD2345"), para que uma troca acidental de algoritmo apareca.
        assert_eq!(
            hash_code("ABCD2345"),
            "a00d76646eba91b057841554d5c8334f498dc592ed744bce404f21fe271cd36e"
        );
    }
}
