//! `users` (RF-04).
//!
//! Every column here is a mirror of the Discord profile. Nothing in this table
//! is authored by the product, so there is no update path other than "Discord
//! told us something changed".

use protocol::scalars::{Snowflake, Timestamp};
use protocol::user::{CurrentUser, UserSummary};
use sqlx::{PgExecutor, PgPool};
use time::OffsetDateTime;
use uuid::Uuid;

use crate::error::{missing, DbResult};

/// One row of `users`.
#[derive(Debug, Clone)]
pub struct UserRow {
    pub id: Uuid,
    pub discord_user_id: i64,
    pub username: String,
    pub display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub created_at: OffsetDateTime,
}

impl UserRow {
    pub fn to_summary(&self) -> UserSummary {
        UserSummary {
            id: self.id,
            discord_user_id: Snowflake::new(self.discord_user_id),
            username: self.username.clone(),
            display_name: self.display_name.clone(),
            avatar_url: self.avatar_url.clone(),
        }
    }

    pub fn to_current(&self) -> CurrentUser {
        CurrentUser {
            id: self.id,
            discord_user_id: Snowflake::new(self.discord_user_id),
            username: self.username.clone(),
            display_name: self.display_name.clone(),
            avatar_url: self.avatar_url.clone(),
            created_at: Timestamp::new(self.created_at),
        }
    }
}

/// Create or refresh the local mirror of a Discord account.
///
/// The id is generated by the caller and only used when the row is new: an
/// existing user keeps the id every foreign key already points at.
pub async fn upsert_from_discord<'e, E: PgExecutor<'e>>(
    executor: E,
    id: Uuid,
    discord_user_id: i64,
    username: &str,
    display_name: Option<&str>,
    avatar_url: Option<&str>,
) -> DbResult<UserRow> {
    let row = sqlx::query_as!(
        UserRow,
        r#"
        INSERT INTO users (id, discord_user_id, username, display_name, avatar_url)
        VALUES ($1, $2, $3, $4, $5)
        ON CONFLICT (discord_user_id) DO UPDATE
           SET username     = EXCLUDED.username,
               display_name = EXCLUDED.display_name,
               avatar_url   = EXCLUDED.avatar_url,
               updated_at   = NOW()
        RETURNING id, discord_user_id, username, display_name, avatar_url, created_at
        "#,
        id,
        discord_user_id,
        username,
        display_name,
        avatar_url,
    )
    .fetch_one(executor)
    .await?;
    Ok(row)
}

pub async fn find_by_id<'e, E: PgExecutor<'e>>(executor: E, id: Uuid) -> DbResult<UserRow> {
    missing(
        "user",
        sqlx::query_as!(
            UserRow,
            r#"
            SELECT id, discord_user_id, username, display_name, avatar_url, created_at
              FROM users
             WHERE id = $1
            "#,
            id,
        )
        .fetch_one(executor)
        .await,
    )
}

pub async fn find_by_discord_id(pool: &PgPool, discord_user_id: i64) -> DbResult<Option<UserRow>> {
    let row = sqlx::query_as!(
        UserRow,
        r#"
        SELECT id, discord_user_id, username, display_name, avatar_url, created_at
          FROM users
         WHERE discord_user_id = $1
        "#,
        discord_user_id,
    )
    .fetch_optional(pool)
    .await?;
    Ok(row)
}
